### ISSUE TITLE
Mandlebrot failures

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [andrewdavidmackenzie/flow#2051]
```
Running unittests examples/mandlebrot/main.rs (target/debug/examples/mandlebrot-11c40667e06098ef)

running 1 test
   Testing /Users/runner/work/flow/flow/flowr/examples/mandlebrot/pixel_to_point/Cargo.toml WASM Project
   Compiling /Users/runner/work/flow/flow/flowr/examples/mandlebrot/pixel_to_point/Cargo.toml WASM project
test test::test_mandlebrot_example has been running for over 60 seconds
   Testing /Users/runner/work/flow/flow/flowr/examples/mandlebrot/escapes/Cargo.toml WASM Project
   Compiling /Users/runner/work/flow/flow/flowr/examples/mandlebrot/escapes/Cargo.toml WASM project
test test::test_mandlebrot_example ... FAILED

failures:

---- test::test_mandlebrot_example stdout ----

	Running example: flowr/examples/mandlebrot
		Runner: flowrcli
		STDIN is read from test.stdin
		Arguments are read from test.args
		STDOUT is saved in test.stdout
		STDERR is saved in test.stderr
		File output is saved in test.file
	Command line: 'flowrcli --native manifest.json test.file [20,15] [[-1.20,0.35],[-1,0.20]]'
thread 'test::test_mandlebrot_example' panicked at flowr/utilities/src/lib.rs:162:13:
Sample "mandlebrot" produced output to STDERR written to 'flowr/examples/mandlebrot/test.stderr'
[2023-09-19T06:53:25Z ERROR flowrlib::checks] Job #33: Runtime error: at file: flowr/src/lib/checks.rs, line: 90
    
                            Function #0 is Blocked, but can_run() returns false
    Job #33: Error State -
             Submission:
              Job Timeout: None
                    Debug: false
                 Manifest: 
             Function #0 Implementation: lib://flowstdlib/data/enumerate
             Function #1 Implementation: lib://flowstdlib/math/subtract
             Function #2 Implementation: lib://flowstdlib/math/range_split
             Function #3 Implementation: lib://flowstdlib/control/join
             Function #4 Implementation: lib://flowstdlib/data/duplicate
             Function #5 Implementation: lib://flowstdlib/data/zip
             Function #6 Implementation: context://args/get
             Function #7 Implementation: context://image/image_buffer
             Function #8 Implementation: file:///Users/runner/work/flow/flow/flowr/examples/mandlebrot/pixel_to_point.wasm
             Function #9 Implementation: file:///Users/runner/work/flow/flow/flowr/examples/mandlebrot/escapes.wasm
    
    RunState:
              Jobs Created: 37
    Number of Jobs Running: 3
              Jobs Running: [35, 36, 34]
         Functions Blocked: {0}
                    Blocks: {#6(1) -> #7(4):2, #6(1) -> #7(4):3, #6(1) -> #8(4):0, #0(2) -> #8(4):1, #2(3) -> #3(2):1, #6(1) -> #8(4):2, #2(3) -> #4(2):0, #6(1) -> #3(2):0}
           Functions Ready: [37]
       Functions Completed: {6}
                Flows Busy: {2: [4, 3, 0], 4: [8]}
            Pending Unblocks: {4: {8}, 2: {4, 3, 0}}

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    test::test_mandlebrot_example

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 146.88s

error: test failed, to rerun pass `-p flowr --example mandlebrot`
Error: The process '/Users/runner/.cargo/bin/cargo' failed with exit code [101](https://github.com/andrewdavidmackenzie/flow/actions/runs/6232026343/job/16914472972?pr=2050#step:14:102)
```

**Comment by andrewdavidmackenzie** [comment]
Happened on macos in CI also:

```
Running unittests examples/mandlebrot/main.rs (target/debug/examples/mandlebrot-d02a426c7d0a0bb9)

running 1 test
   Testing /Users/runner/work/flow/flow/flowr/examples/mandlebrot/pixel_to_point/Cargo.toml WASM Project
   Compiling /Users/runner/work/flow/flow/flowr/examples/mandlebrot/pixel_to_point/Cargo.toml WASM project
test test::test_mandlebrot_example has been running for over 60 seconds
   Testing /Users/runner/work/flow/flow/flowr/examples/mandlebrot/escapes/Cargo.toml WASM Project
   Compiling /Users/runner/work/flow/flow/flowr/examples/mandlebrot/escapes/Cargo.toml WASM project
test test::test_mandlebrot_example ... FAILED

failures:

---- test::test_mandlebrot_example stdout ----

	Running example: flowr/examples/mandlebrot
		Runner: flowrcli
		STDIN is read from test.stdin
		Arguments are read from test.args
		STDOUT is saved in test.stdout
		STDERR is saved in test.stderr
		File output is saved in test.file
	Command line: 'flowrcli --native manifest.json test.file [20,15] [[-1.20,0.35],[-1,0.20]]'
thread 'test::test_mandlebrot_example' panicked at flowr/utilities/src/lib.rs:162:13:
Sample "mandlebrot" produced output to STDERR written to 'flowr/examples/mandlebrot/test.stderr'
[2023-09-26T06:27:55Z ERROR flowrlib::checks] Job #31: Runtime error: at file: flowr/src/lib/checks.rs, line: 90
    
                            Function #0 is Blocked, but can_run() returns false
    Job #31: Error State -
             Submission:
              Job Timeout: None
                    Debug: false
                 Manifest: 
             Function #0 Implementation: lib://flowstdlib/data/enumerate
             Function #1 Implementation: lib://flowstdlib/math/subtract
             Function #2 Implementation: lib://flowstdlib/math/range_split
             Function #3 Implementation: lib://flowstdlib/control/join
             Function #4 Implementation: lib://flowstdlib/data/duplicate
             Function #5 Implementation: lib://flowstdlib/data/zip
             Function #6 Implementation: context://args/get
             Function #7 Implementation: context://image/image_buffer
             Function #8 Implementation: file:///Users/runner/work/flow/flow/flowr/examples/mandlebrot/pixel_to_point.wasm
             Function #9 Implementation: file:///Users/runner/work/flow/flow/flowr/examples/mandlebrot/escapes.wasm
    
    RunState:
              Jobs Created: 35
    Number of Jobs Running: 2
              Jobs Running: [34, 33]
         Functions Blocked: {0}
                    Blocks: {#6(1) -> #7(4):3, #6(1) -> #7(4):2, #6(1) -> #8(4):0, #6(1) -> #3(2):0, #2(3) -> #4(2):0, #0(2) -> #8(4):1, #2(3) -> #3(2):1, #6(1) -> #8(4):2}
           Functions Ready: [35]
       Functions Completed: {6}
                Flows Busy: {4: [8], 2: [3, 0]}
            Pending Unblocks: {2: {0, 4, 3}, 4: {8}}

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    test::test_mandlebrot_example

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 130.20s

error: test failed, to rerun pass `-p flowr --example mandlebrot`
Error: The process '/Users/runner/.cargo/bin/cargo' failed with exit code [101](https://github.com/andrewdavidmackenzie/flow/actions/runs/6308800478/job/17127554262?pr=2054#step:14:102)
```
